name: viber-app
title: Viber Desktop
version: 20.3.0.1
base: core22
summary: Viber for Desktop.
description: |
  Free and secure calls and messages to anyone, anywhere, on any device and network, in any country!
  Viber for Desktop syncs your contacts, messages and call history with your mobile device.

grade: stable
confinement: devmode
compression: lzo 
architectures: [amd64]

parts:
  viber:
    plugin: dump
    source: http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
    source-type: deb
    stage-packages:
    - libpulse0
    - libasound2
    - libnss3
    - libgstreamer-plugins-base1.0-0
    - libgstreamer1.0-0
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-pulseaudio
    - gstreamer1.0-libav
    - libxcb-xinput0
    - libstdc++6
    prime: 
    - opt
    - opt/viber/Viber 
    - opt/viber/lib/libQt6WebEngineCore.so.6

apps:
  viber:
    command: desktop-launch $SNAP/opt/viber/Viber
    desktop: snap/gui/Viber.desktop 
    extensions: [kde-neon]
    plugs: 
     - home
     - unity7
     - network
     - x11
     - wayland 
     - desktop
     - desktop-legacy
     - audio-playback 
     - audio-record 
     - camera

